//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTR_Watch_face.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTR_Watch_face.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файлов изображений.
        /// </summary>
        public static string Dialog_Title_Image {
            get {
                return ResourceManager.GetString("Dialog_Title_Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла настроек циферблата.
        /// </summary>
        public static string Dialog_Title_Pack {
            get {
                return ResourceManager.GetString("Dialog_Title_Pack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь к файлу упаковщика.
        /// </summary>
        public static string Dialog_Title_PackUnpack {
            get {
                return ResourceManager.GetString("Dialog_Title_PackUnpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла настроек предпросмотра.
        /// </summary>
        public static string Dialog_Title_PreviewStates {
            get {
                return ResourceManager.GetString("Dialog_Title_PreviewStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить анимированный предпросмотр.
        /// </summary>
        public static string Dialog_Title_SaveGIF {
            get {
                return ResourceManager.GetString("Dialog_Title_SaveGIF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить предпросмотр.
        /// </summary>
        public static string Dialog_Title_SavePNG {
            get {
                return ResourceManager.GetString("Dialog_Title_SavePNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбор файла циферблата.
        /// </summary>
        public static string Dialog_Title_Unpack {
            get {
                return ResourceManager.GetString("Dialog_Title_Unpack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на \readme.chm.
        /// </summary>
        public static string File_ReadMy {
            get {
                return ResourceManager.GetString("File_ReadMy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр.
        /// </summary>
        public static string Form_Preview {
            get {
                return ResourceManager.GetString("Form_Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предпросмотр [X=.
        /// </summary>
        public static string Form_PreviewX {
            get {
                return ResourceManager.GetString("Form_PreviewX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Большой размер файла.
        /// </summary>
        public static string Message_bigFile_Caption {
            get {
                return ResourceManager.GetString("Message_bigFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер несжатого файла превышает 1,95МБ..
        /// </summary>
        public static string Message_bigFile_Text1 {
            get {
                return ResourceManager.GetString("Message_bigFile_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Размер несжатого файла превышает 1,5МБ..
        /// </summary>
        public static string Message_bigFile_Text1_gts {
            get {
                return ResourceManager.GetString("Message_bigFile_Text1_gts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Циферблат может не работать..
        /// </summary>
        public static string Message_bigFile_Text2 {
            get {
                return ResourceManager.GetString("Message_bigFile_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Координаты скопированны.
        /// </summary>
        public static string Message_CopyCoord {
            get {
                return ResourceManager.GetString("Message_CopyCoord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка.
        /// </summary>
        public static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Невозможно открыть изображение: .
        /// </summary>
        public static string Message_error_Image_Text1 {
            get {
                return ResourceManager.GetString("Message_error_Image_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на . У Вас нет прав на чтение файла, или изображение повреждено..
        /// </summary>
        public static string Message_error_Image_Text2 {
            get {
                return ResourceManager.GetString("Message_error_Image_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Файл не найден.
        /// </summary>
        public static string Message_error_pack_unpack_dir_Caption {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Путь [.
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text1 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ] к утилите распаковки/запаковки указан неверно..
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text2 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Укажите верный путь к утилите распаковки/запаковки..
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text3 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют необходимые компоненты программы..
        /// </summary>
        public static string Message_error_respackerPath_Text1 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не найдена утилита сжатия bin файлов по пути [.
        /// </summary>
        public static string Message_error_respackerPath_Text2 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Проверьте наличие утилиты сжатия bin файлов..
        /// </summary>
        public static string Message_error_respackerPath_Text3 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу.
        /// </summary>
        public static string Message_GoToFile_Caption {
            get {
                return ResourceManager.GetString("Message_GoToFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перейти к файлу?.
        /// </summary>
        public static string Message_GoToFile_Text {
            get {
                return ResourceManager.GetString("Message_GoToFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверный JSON файл..
        /// </summary>
        public static string Message_JsonError_Text {
            get {
                return ResourceManager.GetString("Message_JsonError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ошибка чтения JSON файла..
        /// </summary>
        public static string Message_JsonReadError_Text {
            get {
                return ResourceManager.GetString("Message_JsonReadError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузка настроек предпросмотра.
        /// </summary>
        public static string Message_LoadPreviewStates_Caption {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Загрузить имеющийся файл с набором параметров предпросмотра PreviewStates.json?.
        /// </summary>
        public static string Message_LoadPreviewStates_Text {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открытие проекта.
        /// </summary>
        public static string Message_openProject_Caption {
            get {
                return ResourceManager.GetString("Message_openProject_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Открыть распакованный проект?.
        /// </summary>
        public static string Message_openProject_Text {
            get {
                return ResourceManager.GetString("Message_openProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG файлы идут не по порядку или часть файлов отсутствует..
        /// </summary>
        public static string Message_PNGmissing_Text1 {
            get {
                return ResourceManager.GetString("Message_PNGmissing_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Присвойте имена PNG файлам в порядке возрастания..
        /// </summary>
        public static string Message_PNGmissing_Text2 {
            get {
                return ResourceManager.GetString("Message_PNGmissing_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезагрузка.
        /// </summary>
        public static string Message_Restart_Caption {
            get {
                return ResourceManager.GetString("Message_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для применения настроек необходимо перезагрузить программу..
        /// </summary>
        public static string Message_Restart_Text1 {
            get {
                return ResourceManager.GetString("Message_Restart_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перезапустить программу?.
        /// </summary>
        public static string Message_Restart_Text2 {
            get {
                return ResourceManager.GetString("Message_Restart_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для сохранения предустановленных параметром установите хотябы в одном поле &quot;Калории&quot; значение отличное от &quot;1234&quot;..
        /// </summary>
        public static string Message_SaveOnly1234_Text {
            get {
                return ResourceManager.GetString("Message_SaveOnly1234_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Предупреждение.
        /// </summary>
        public static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Если использовать не все три стрелки в аналоговых часах, то могут возникнуть проблемы..
        /// </summary>
        public static string Message_Warning3clockHand_Text {
            get {
                return ResourceManager.GetString("Message_Warning3clockHand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не рекомендуется использовать отображение расстояния без суффикса..
        /// </summary>
        public static string Message_WarningDistanceSuffix {
            get {
                return ResourceManager.GetString("Message_WarningDistanceSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не рекомендуется использовать минуты без использования часов для числового отображения времени..
        /// </summary>
        public static string Message_WarningOnlyMin_Text {
            get {
                return ResourceManager.GetString("Message_WarningOnlyMin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не рекомендуется использовать ctreyls без использования часов и минут для числового отображения времени..
        /// </summary>
        public static string Message_WarningOnlySec_Text {
            get {
                return ResourceManager.GetString("Message_WarningOnlySec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Разные значения ImageIndex для десятков и единиц не поддерживаются..
        /// </summary>
        public static string Message_WarningTensOnes_Text {
            get {
                return ResourceManager.GetString("Message_WarningTensOnes_Text", resourceCulture);
            }
        }
    }
}
