//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GTR_Watch_face.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class FormStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal FormStrings() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GTR_Watch_face.Properties.FormStrings", typeof(FormStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Большой размер файла.
        /// </summary>
        public static string Message_bigFile_Caption {
            get {
                return ResourceManager.GetString("Message_bigFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Размер несжатого файла превышает 1,95МБ..
        /// </summary>
        public static string Message_bigFile_Text1 {
            get {
                return ResourceManager.GetString("Message_bigFile_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Циферблат может не работать..
        /// </summary>
        public static string Message_bigFile_Text2 {
            get {
                return ResourceManager.GetString("Message_bigFile_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Ошибка.
        /// </summary>
        public static string Message_Error_Caption {
            get {
                return ResourceManager.GetString("Message_Error_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Невозможно открыть изображение: .
        /// </summary>
        public static string Message_error_Image_Text1 {
            get {
                return ResourceManager.GetString("Message_error_Image_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// У Вас нет прав на чтение файла, или изображение повреждено..
        /// </summary>
        public static string Message_error_Image_Text2 {
            get {
                return ResourceManager.GetString("Message_error_Image_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Файл не найден.
        /// </summary>
        public static string Message_error_pack_unpack_dir_Caption {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Путь [.
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text1 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// ] к утилите распаковки/запаковки указан неверно..
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text2 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Укажите верный путь к утилите распаковки/запаковки..
        /// </summary>
        public static string Message_error_pack_unpack_dir_Text3 {
            get {
                return ResourceManager.GetString("Message_error_pack_unpack_dir_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Отсутствуют необходимые компоненты программы..
        /// </summary>
        public static string Message_error_respackerPath_Text1 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Не найдена утилита сжатия bin файлов по пути [.
        /// </summary>
        public static string Message_error_respackerPath_Text2 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Проверьте наличие утилиты сжатия bin файлов..
        /// </summary>
        public static string Message_error_respackerPath_Text3 {
            get {
                return ResourceManager.GetString("Message_error_respackerPath_Text3", resourceCulture);
            }
        }
        
        /// <summary>
        /// Перейти к файлу.
        /// </summary>
        public static string Message_GoToFile_Caption {
            get {
                return ResourceManager.GetString("Message_GoToFile_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Перейти к файлу?.
        /// </summary>
        public static string Message_GoToFile_Text {
            get {
                return ResourceManager.GetString("Message_GoToFile_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Неверный JSON файл..
        /// </summary>
        public static string Message_JsonError_Text {
            get {
                return ResourceManager.GetString("Message_JsonError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Ошибка чтения JSON файла..
        /// </summary>
        public static string Message_JsonReadError_Text {
            get {
                return ResourceManager.GetString("Message_JsonReadError_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Загрузка настроек предпросмотра.
        /// </summary>
        public static string Message_LoadPreviewStates_Caption {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Загрузить имеющийся файл с набором параметров предпросмотра PreviewStates.json?.
        /// </summary>
        public static string Message_LoadPreviewStates_Text {
            get {
                return ResourceManager.GetString("Message_LoadPreviewStates_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Открытие проекта.
        /// </summary>
        public static string Message_openProject_Caption {
            get {
                return ResourceManager.GetString("Message_openProject_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Открыть распакованный проект?.
        /// </summary>
        public static string Message_openProject_Text {
            get {
                return ResourceManager.GetString("Message_openProject_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// PNG файлы идут не по порядку или часть файлов отсутствует..
        /// </summary>
        public static string Message_PNGmissing_Text1 {
            get {
                return ResourceManager.GetString("Message_PNGmissing_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Присвойте имена PNG файлам в порядке возрастания..
        /// </summary>
        public static string Message_PNGmissing_Text2 {
            get {
                return ResourceManager.GetString("Message_PNGmissing_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Перезагрузка.
        /// </summary>
        public static string Message_Restart_Caption {
            get {
                return ResourceManager.GetString("Message_Restart_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Для применения настроек необходимо перезагрузить программу..
        /// </summary>
        public static string Message_Restart_Text1 {
            get {
                return ResourceManager.GetString("Message_Restart_Text1", resourceCulture);
            }
        }
        
        /// <summary>
        /// Перезапустить программу?.
        /// </summary>
        public static string Message_Restart_Text2 {
            get {
                return ResourceManager.GetString("Message_Restart_Text2", resourceCulture);
            }
        }
        
        /// <summary>
        /// Для сохранения предустановленных параметром установите хотябы в одном поле &quot;Калории&quot; значение отличное от &quot;1234&quot;..
        /// </summary>
        public static string Message_SaveOnly1234_Text {
            get {
                return ResourceManager.GetString("Message_SaveOnly1234_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Предупреждение.
        /// </summary>
        public static string Message_Warning_Caption {
            get {
                return ResourceManager.GetString("Message_Warning_Caption", resourceCulture);
            }
        }
        
        /// <summary>
        /// Если использовать не все три стрелки в аналоговых часах, то могут возникнуть проблемы..
        /// </summary>
        public static string Message_Warning3clockHand_Text {
            get {
                return ResourceManager.GetString("Message_Warning3clockHand_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Не рекомендуется использовать минуты без использования часов для числового отображения времени..
        /// </summary>
        public static string Message_WarningOnlyMin_Text {
            get {
                return ResourceManager.GetString("Message_WarningOnlyMin_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Не рекомендуется использовать ctreyls без использования часов и минут для числового отображения времени..
        /// </summary>
        public static string Message_WarningOnlySec_Text {
            get {
                return ResourceManager.GetString("Message_WarningOnlySec_Text", resourceCulture);
            }
        }
        
        /// <summary>
        /// Разные значения ImageIndex для десятков и единиц не поддерживаются..
        /// </summary>
        public static string Message_WarningTensOnes_Text {
            get {
                return ResourceManager.GetString("Message_WarningTensOnes_Text", resourceCulture);
            }
        }
    }
}
